name: Bot Status

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
  
jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        uses: sisodiya2421/pinger@master
        env:
          URL: News-TelegramBot.nclsbayona.repl.co
          
  send_notification:
    name: Notification for Telegram
    needs: status
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message for failure
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Dear ${{ secrets.TELEGRAM_TO }} on the repository ${{ github.repository }} the status build is failing, please check repl.it
